# Generated by Django 3.0.4 on 2020-03-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfollio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('contact', models.CharField(max_length=254)),
                ('birthdate', models.DateField(default=None)),
                ('image', models.ImageField(default='default.jpg', upload_to='portfollio_images')),
                ('image2', models.ImageField(default='default.jpg', upload_to='portfollio_images')),
                ('current_city', models.CharField(max_length=250)),
                ('current_country', models.CharField(max_length=250)),
                ('current_location', models.CharField(max_length=250)),
                ('job_title', models.CharField(max_length=250)),
            ],
        ),
    ]
