# Generated by Django 3.0.4 on 2020-03-27 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfollio', '0002_auto_20200327_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=250)),
                ('start_date', models.CharField(max_length=250)),
                ('end_date', models.CharField(max_length=250)),
                ('university', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
