# Generated by Django 3.0.4 on 2020-03-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfollio', '0003_education'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('icon', models.CharField(max_length=250)),
                ('desc', models.TextField()),
            ],
        ),
    ]
