# Generated by Django 3.0.4 on 2020-03-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfollio', '0007_contact_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMeMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
